### ISSUE TITLE
New icon / logo

### ISSUE THREAD

**Issue by mansya** [AmeerHamzaaa/TNImageView-Android#3]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by yohamza** [comment]
I will love it @mansya  :)

**Comment by mansya** [comment]
I have designed a logo for this project. What do you think ? do you like it ?
![tnimage view](https://user-images.githubusercontent.com/33461607/41020156-fa9b19bc-698b-11e8-88fa-6ebcc473da03.png)

**Comment by yohamza** [comment]
Can you make it more minimal with a solid color?

**Comment by mansya** [comment]
do you mean like this ?
![tnimage view](https://user-images.githubusercontent.com/33461607/41047732-6c5897be-69d7-11e8-84a7-c69b0c33a73e.png)

**Comment by yohamza** [comment]
Yes I like this one what about changing coloor to blue and only single image icon in center? What do you say?

**Comment by mansya** [comment]
yes. I agree. actually i was also bothered with 2 pictures in the middle.
i will change it. would you give me the RGB color code?

**Comment by yohamza** [comment]
#3b5998 This is the hex and 59,89,152 these are RGB's

**Comment by mansya** [comment]
it's look ok ?
![tnimage view](https://user-images.githubusercontent.com/33461607/41091571-0cb94016-6a71-11e8-8b35-da461593d3c1.png)

**Comment by yohamza** [comment]
yes now it looks good. So now make the center image's borders curved like the icon has.

**Comment by mansya** [comment]
Did you mean like this ?
![banner](https://user-images.githubusercontent.com/33461607/41116021-61f034ee-6ab3-11e8-8690-ff42f91b517c.png)

**Comment by yohamza** [comment]
Great @mansya

**Comment by mansya** [comment]
I have uploaded all files to this link.
https://drive.google.com/open?id=144qXXhlECAJeVrCCd0TxOFBGBR4FVoFJ

and I have also sent you pull requests. please check
